name: Release
on:
  push:
    branches:
    - main
    tags:
    - "v*"

jobs:
  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
      with:
        extraFiles: "[\".github/scripts/*\", \".github/workflows/ci.yml\", \"*.sh\"]"
        extraKey: "release"
    - uses: coursier/setup-action@v1.3
      with:
        jvm: 8
    - run: .github/scripts/gpg-setup.sh
      env:
        PGP_SECRET: ${{ secrets.PUBLISH_SECRET_KEY }}
    - run: ./mill resolve __
      shell: bash
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jars
        path: |
          out
